/*
 * This source file was generated by the Gradle 'init' task
 */
package edu.duke.ece651.simulationserver;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;

public class App {
  SimulationTextView view;

  public App(String jsonFile, BufferedReader br) throws IOException {
    view = new SimulationTextView(jsonFile, br);
  }
  
  // public String getGreeting() {
  //   return "Hello World!";
  // }

  public static void main(String[] args) throws IOException {
    if (args.length != 1) {
      System.err.println("Usage: simulation <jsonInputFile>");
      return;
      // System.exit(1);
    }
    String JsonFile = args[0];
    BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
    App app = new App(JsonFile, br);
    app.view.run();
  }
}
