/*
 * This source file was generated by the Gradle 'init' task
 */
package edu.duke.ece651.simulationserver;

public class SimulationServer {
    public String getGreeting() {
        return "Hello World!";
    }
    public static void main(String[] args) {
      // System.out.println(new SimulationServer().getGreeting());
    }
}
